services:
  # PostgreSQL database
  postgres:
    image: postgres:18.1-bookworm
    container_name: epam-postgres
    ports:
      - "5432:5432" #! vulnerability?
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - epampgdata:/var/lib/postgresql/
    healthcheck: # This is neccessary to avoid race condition when backend container tries to run migrations when postgres container did not initialize fully
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 5s
      retries: 15
    restart: unless-stopped

  # FastAPI backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: epam-backend
    depends_on:
      postgres:
        condition: service_healthy # This checks the condition of postgres container before running migrations
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend:/app/
    restart: unless-stopped

volumes:
  epampgdata:
