"""Updated Document table in Database to account for AWS S3 uploads

Revision ID: e775848fbcf9
Revises: 3b97337f8e79
Create Date: 2026-03-12 19:28:10.681264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e775848fbcf9"
down_revision: Union[str, Sequence[str], None] = "3b97337f8e79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "CREATE TYPE documentstatus AS ENUM ('PENDING', 'UPLOADED', 'PROCESSED', 'FAILED')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "UPLOADED", "PROCESSED", "FAILED", name="documentstatus"
            ),
            nullable=False,
        ),
    )
    op.add_column("document", sa.Column("uploaded_at", sa.DateTime(), nullable=True))
    op.alter_column("document", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("document", "size", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("document_name_key"), "document", type_="unique")
    op.drop_column("document", "storage_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("storage_key", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        op.f("document_name_key"),
        "document",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("document", "size", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("document", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("document", "uploaded_at")
    op.drop_column("document", "status")

    op.execute("DROP TYPE documentstatus")
    # ### end Alembic commands ###
